export const RELATIONSHIP_STATE=Object.freeze({
  CONFIRMED_CITATION:'CONFIRMED_CITATION_DEPENDENCY',
  CONFIRMED_QUOTE:'CONFIRMED_QUOTE_REUSE',
  POSSIBLE:'POSSIBLE_RELATED_PROPOSITION',
  UNCONFIRMED:'CANDIDATE_UNCONFIRMED',
  NOT_RELATED:'NOT_RELATED'
});

export const INCIDENT_TYPE=Object.freeze({
  FABRICATED_AUTHORITY:'FABRICATED_AUTHORITY',
  CITATION_ERROR:'CITATION_ERROR',
  QUOTATION_DISCREPANCY:'QUOTATION_DISCREPANCY',
  WITHDRAWN_AUTHORITY:'WITHDRAWN_AUTHORITY',
  OVERRULED_AUTHORITY:'OVERRULED_AUTHORITY',
  UNSUPPORTED_PROPOSITION:'UNSUPPORTED_PROPOSITION',
  USER_REVIEW:'USER_REVIEW',
  OTHER:'OTHER'
});

export const INCIDENT_SOURCE_TYPE=Object.freeze({
  COURT_ORDER:'COURT_ORDER',
  SANCTIONS_ORDER:'SANCTIONS_ORDER',
  JUDICIAL_OPINION:'JUDICIAL_OPINION',
  USER_REPORT:'USER_REPORT',
  OTHER:'OTHER'
});

export const DEPENDENCY_TYPE=Object.freeze({
  AUTHORITY:'AUTHORITY',
  QUOTATION:'QUOTATION',
  PROPOSITION:'PROPOSITION'
});

export const INCIDENT_REVIEW_STATUS=Object.freeze({
  CONFIRMED_FROM_INCIDENT_SOURCE:'CONFIRMED_FROM_INCIDENT_SOURCE',
  USER_FLAGGED:'USER_FLAGGED',
  UNRESOLVED:'UNRESOLVED'
});

export const SOURCE_STATE=Object.freeze({
  LIVE:'LIVE',
  CACHED:'CACHED',
  RECORDED:'RECORDED',
  UNAVAILABLE:'SOURCE_UNAVAILABLE',
  RATE_LIMITED:'RATE_LIMITED',
  AUTH_ERROR:'AUTH_ERROR'
});

export const SOURCE_TEXT_TYPE=Object.freeze({
  RECAP_PLAIN_TEXT:'RECAP_PLAIN_TEXT',
  FIRECRAWL_PUBLIC_SOURCE:'FIRECRAWL_PUBLIC_SOURCE',
  COURTLISTENER_SNIPPET:'COURTLISTENER_SNIPPET',
  RECORDED_PUBLIC_SOURCE:'RECORDED_PUBLIC_SOURCE',
  COURT_ORDER_RECORD_OF_FILING:'COURT_ORDER_RECORD_OF_FILING'
});

export function relationshipLabel(state){
  switch(state){
    case RELATIONSHIP_STATE.CONFIRMED_CITATION:return 'Confirmed citation';
    case RELATIONSHIP_STATE.CONFIRMED_QUOTE:return 'Confirmed quote';
    case RELATIONSHIP_STATE.POSSIBLE:return 'Possible related proposition';
    case RELATIONSHIP_STATE.UNCONFIRMED:return 'Could not confirm';
    case RELATIONSHIP_STATE.NOT_RELATED:return 'Not related';
    default:return 'Unknown';
  }
}

export function isConfirmedRelationship(state){
  return state===RELATIONSHIP_STATE.CONFIRMED_CITATION||state===RELATIONSHIP_STATE.CONFIRMED_QUOTE;
}
